/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnohdinSalasananRouteImport } from './routes/unohdin-salasanan'
import { Route as TurvallisuusRouteImport } from './routes/turvallisuus'
import { Route as TukiRouteImport } from './routes/tuki'
import { Route as TietosuojaRouteImport } from './routes/tietosuoja'
import { Route as TietojaRouteImport } from './routes/tietoja'
import { Route as SaannotRouteImport } from './routes/saannot'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RekisteroidyRouteImport } from './routes/rekisteroidy'
import { Route as KirjauduRouteImport } from './routes/kirjaudu'
import { Route as KayttoehdotRouteImport } from './routes/kayttoehdot'
import { Route as HinnatRouteImport } from './routes/hinnat'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTilaaPlusRouteImport } from './routes/_authenticated/tilaa-plus'
import { Route as AuthenticatedTapahtumatRouteImport } from './routes/_authenticated/tapahtumat'
import { Route as AuthenticatedRyhmatRouteImport } from './routes/_authenticated/ryhmat'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedPoistuRouteImport } from './routes/_authenticated/poistu'
import { Route as AuthenticatedPisteetRouteImport } from './routes/_authenticated/pisteet'
import { Route as AuthenticatedOmaProfiiliRouteImport } from './routes/_authenticated/oma-profiili'
import { Route as AuthenticatedKalenteriRouteImport } from './routes/_authenticated/kalenteri'
import { Route as AuthenticatedHaeRouteImport } from './routes/_authenticated/hae'
import { Route as AuthenticatedAsetuksetRouteImport } from './routes/_authenticated/asetukset'
import { Route as AuthenticatedAloitusRouteImport } from './routes/_authenticated/aloitus'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedViestitIndexRouteImport } from './routes/_authenticated/viestit.index'
import { Route as AuthenticatedPlusIndexRouteImport } from './routes/_authenticated/plus.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedViestitIdRouteImport } from './routes/_authenticated/viestit.$id'
import { Route as AuthenticatedTreffijutteluMatchIdRouteImport } from './routes/_authenticated/treffijuttelu.$matchId'
import { Route as AuthenticatedProfiiliIdRouteImport } from './routes/_authenticated/profiili.$id'
import { Route as AuthenticatedPlusSelaaRouteImport } from './routes/_authenticated/plus.selaa'
import { Route as AuthenticatedPlusAsetuksetRouteImport } from './routes/_authenticated/plus.asetukset'
import { Route as AuthenticatedEnsifiilisIdRouteImport } from './routes/_authenticated/ensifiilis.$id'
import { Route as AuthenticatedAdminTilauksetRouteImport } from './routes/_authenticated/admin.tilaukset'
import { Route as AuthenticatedAdminTapahtumatRouteImport } from './routes/_authenticated/admin.tapahtumat'
import { Route as AuthenticatedAdminModerointiRouteImport } from './routes/_authenticated/admin.moderointi'
import { Route as AuthenticatedAdminKayttajatRouteImport } from './routes/_authenticated/admin.kayttajat'
import { Route as AuthenticatedAdminIlmoituksetRouteImport } from './routes/_authenticated/admin.ilmoitukset'
import { Route as AuthenticatedAdminGdprRouteImport } from './routes/_authenticated/admin.gdpr'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedPlusProfiiliIdRouteImport } from './routes/_authenticated/plus.profiili.$id'

const UnohdinSalasananRoute = UnohdinSalasananRouteImport.update({
  id: '/unohdin-salasanan',
  path: '/unohdin-salasanan',
  getParentRoute: () => rootRouteImport,
} as any)
const TurvallisuusRoute = TurvallisuusRouteImport.update({
  id: '/turvallisuus',
  path: '/turvallisuus',
  getParentRoute: () => rootRouteImport,
} as any)
const TukiRoute = TukiRouteImport.update({
  id: '/tuki',
  path: '/tuki',
  getParentRoute: () => rootRouteImport,
} as any)
const TietosuojaRoute = TietosuojaRouteImport.update({
  id: '/tietosuoja',
  path: '/tietosuoja',
  getParentRoute: () => rootRouteImport,
} as any)
const TietojaRoute = TietojaRouteImport.update({
  id: '/tietoja',
  path: '/tietoja',
  getParentRoute: () => rootRouteImport,
} as any)
const SaannotRoute = SaannotRouteImport.update({
  id: '/saannot',
  path: '/saannot',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RekisteroidyRoute = RekisteroidyRouteImport.update({
  id: '/rekisteroidy',
  path: '/rekisteroidy',
  getParentRoute: () => rootRouteImport,
} as any)
const KirjauduRoute = KirjauduRouteImport.update({
  id: '/kirjaudu',
  path: '/kirjaudu',
  getParentRoute: () => rootRouteImport,
} as any)
const KayttoehdotRoute = KayttoehdotRouteImport.update({
  id: '/kayttoehdot',
  path: '/kayttoehdot',
  getParentRoute: () => rootRouteImport,
} as any)
const HinnatRoute = HinnatRouteImport.update({
  id: '/hinnat',
  path: '/hinnat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTilaaPlusRoute = AuthenticatedTilaaPlusRouteImport.update({
  id: '/tilaa-plus',
  path: '/tilaa-plus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTapahtumatRoute = AuthenticatedTapahtumatRouteImport.update({
  id: '/tapahtumat',
  path: '/tapahtumat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRyhmatRoute = AuthenticatedRyhmatRouteImport.update({
  id: '/ryhmat',
  path: '/ryhmat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPoistuRoute = AuthenticatedPoistuRouteImport.update({
  id: '/poistu',
  path: '/poistu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPisteetRoute = AuthenticatedPisteetRouteImport.update({
  id: '/pisteet',
  path: '/pisteet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOmaProfiiliRoute =
  AuthenticatedOmaProfiiliRouteImport.update({
    id: '/oma-profiili',
    path: '/oma-profiili',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalenteriRoute = AuthenticatedKalenteriRouteImport.update({
  id: '/kalenteri',
  path: '/kalenteri',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHaeRoute = AuthenticatedHaeRouteImport.update({
  id: '/hae',
  path: '/hae',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsetuksetRoute = AuthenticatedAsetuksetRouteImport.update({
  id: '/asetukset',
  path: '/asetukset',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAloitusRoute = AuthenticatedAloitusRouteImport.update({
  id: '/aloitus',
  path: '/aloitus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViestitIndexRoute =
  AuthenticatedViestitIndexRouteImport.update({
    id: '/viestit/',
    path: '/viestit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusIndexRoute = AuthenticatedPlusIndexRouteImport.update({
  id: '/plus/',
  path: '/plus/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedViestitIdRoute = AuthenticatedViestitIdRouteImport.update({
  id: '/viestit/$id',
  path: '/viestit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreffijutteluMatchIdRoute =
  AuthenticatedTreffijutteluMatchIdRouteImport.update({
    id: '/treffijuttelu/$matchId',
    path: '/treffijuttelu/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfiiliIdRoute = AuthenticatedProfiiliIdRouteImport.update({
  id: '/profiili/$id',
  path: '/profiili/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusSelaaRoute = AuthenticatedPlusSelaaRouteImport.update({
  id: '/plus/selaa',
  path: '/plus/selaa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlusAsetuksetRoute =
  AuthenticatedPlusAsetuksetRouteImport.update({
    id: '/plus/asetukset',
    path: '/plus/asetukset',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnsifiilisIdRoute =
  AuthenticatedEnsifiilisIdRouteImport.update({
    id: '/ensifiilis/$id',
    path: '/ensifiilis/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTilauksetRoute =
  AuthenticatedAdminTilauksetRouteImport.update({
    id: '/tilaukset',
    path: '/tilaukset',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTapahtumatRoute =
  AuthenticatedAdminTapahtumatRouteImport.update({
    id: '/tapahtumat',
    path: '/tapahtumat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerointiRoute =
  AuthenticatedAdminModerointiRouteImport.update({
    id: '/moderointi',
    path: '/moderointi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKayttajatRoute =
  AuthenticatedAdminKayttajatRouteImport.update({
    id: '/kayttajat',
    path: '/kayttajat',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIlmoituksetRoute =
  AuthenticatedAdminIlmoituksetRouteImport.update({
    id: '/ilmoitukset',
    path: '/ilmoitukset',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGdprRoute = AuthenticatedAdminGdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlusProfiiliIdRoute =
  AuthenticatedPlusProfiiliIdRouteImport.update({
    id: '/plus/profiili/$id',
    path: '/plus/profiili/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hinnat': typeof HinnatRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saannot': typeof SaannotRoute
  '/tietoja': typeof TietojaRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/tuki': typeof TukiRoute
  '/turvallisuus': typeof TurvallisuusRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/aloitus': typeof AuthenticatedAloitusRoute
  '/asetukset': typeof AuthenticatedAsetuksetRoute
  '/hae': typeof AuthenticatedHaeRoute
  '/kalenteri': typeof AuthenticatedKalenteriRoute
  '/oma-profiili': typeof AuthenticatedOmaProfiiliRoute
  '/pisteet': typeof AuthenticatedPisteetRoute
  '/poistu': typeof AuthenticatedPoistuRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ryhmat': typeof AuthenticatedRyhmatRoute
  '/tapahtumat': typeof AuthenticatedTapahtumatRoute
  '/tilaa-plus': typeof AuthenticatedTilaaPlusRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/admin/ilmoitukset': typeof AuthenticatedAdminIlmoituksetRoute
  '/admin/kayttajat': typeof AuthenticatedAdminKayttajatRoute
  '/admin/moderointi': typeof AuthenticatedAdminModerointiRoute
  '/admin/tapahtumat': typeof AuthenticatedAdminTapahtumatRoute
  '/admin/tilaukset': typeof AuthenticatedAdminTilauksetRoute
  '/ensifiilis/$id': typeof AuthenticatedEnsifiilisIdRoute
  '/plus/asetukset': typeof AuthenticatedPlusAsetuksetRoute
  '/plus/selaa': typeof AuthenticatedPlusSelaaRoute
  '/profiili/$id': typeof AuthenticatedProfiiliIdRoute
  '/treffijuttelu/$matchId': typeof AuthenticatedTreffijutteluMatchIdRoute
  '/viestit/$id': typeof AuthenticatedViestitIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/plus/': typeof AuthenticatedPlusIndexRoute
  '/viestit/': typeof AuthenticatedViestitIndexRoute
  '/plus/profiili/$id': typeof AuthenticatedPlusProfiiliIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hinnat': typeof HinnatRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saannot': typeof SaannotRoute
  '/tietoja': typeof TietojaRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/tuki': typeof TukiRoute
  '/turvallisuus': typeof TurvallisuusRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/aloitus': typeof AuthenticatedAloitusRoute
  '/asetukset': typeof AuthenticatedAsetuksetRoute
  '/hae': typeof AuthenticatedHaeRoute
  '/kalenteri': typeof AuthenticatedKalenteriRoute
  '/oma-profiili': typeof AuthenticatedOmaProfiiliRoute
  '/pisteet': typeof AuthenticatedPisteetRoute
  '/poistu': typeof AuthenticatedPoistuRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/ryhmat': typeof AuthenticatedRyhmatRoute
  '/tapahtumat': typeof AuthenticatedTapahtumatRoute
  '/tilaa-plus': typeof AuthenticatedTilaaPlusRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/admin/ilmoitukset': typeof AuthenticatedAdminIlmoituksetRoute
  '/admin/kayttajat': typeof AuthenticatedAdminKayttajatRoute
  '/admin/moderointi': typeof AuthenticatedAdminModerointiRoute
  '/admin/tapahtumat': typeof AuthenticatedAdminTapahtumatRoute
  '/admin/tilaukset': typeof AuthenticatedAdminTilauksetRoute
  '/ensifiilis/$id': typeof AuthenticatedEnsifiilisIdRoute
  '/plus/asetukset': typeof AuthenticatedPlusAsetuksetRoute
  '/plus/selaa': typeof AuthenticatedPlusSelaaRoute
  '/profiili/$id': typeof AuthenticatedProfiiliIdRoute
  '/treffijuttelu/$matchId': typeof AuthenticatedTreffijutteluMatchIdRoute
  '/viestit/$id': typeof AuthenticatedViestitIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/plus': typeof AuthenticatedPlusIndexRoute
  '/viestit': typeof AuthenticatedViestitIndexRoute
  '/plus/profiili/$id': typeof AuthenticatedPlusProfiiliIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/hinnat': typeof HinnatRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kirjaudu': typeof KirjauduRoute
  '/rekisteroidy': typeof RekisteroidyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saannot': typeof SaannotRoute
  '/tietoja': typeof TietojaRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/tuki': typeof TukiRoute
  '/turvallisuus': typeof TurvallisuusRoute
  '/unohdin-salasanan': typeof UnohdinSalasananRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/aloitus': typeof AuthenticatedAloitusRoute
  '/_authenticated/asetukset': typeof AuthenticatedAsetuksetRoute
  '/_authenticated/hae': typeof AuthenticatedHaeRoute
  '/_authenticated/kalenteri': typeof AuthenticatedKalenteriRoute
  '/_authenticated/oma-profiili': typeof AuthenticatedOmaProfiiliRoute
  '/_authenticated/pisteet': typeof AuthenticatedPisteetRoute
  '/_authenticated/poistu': typeof AuthenticatedPoistuRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/ryhmat': typeof AuthenticatedRyhmatRoute
  '/_authenticated/tapahtumat': typeof AuthenticatedTapahtumatRoute
  '/_authenticated/tilaa-plus': typeof AuthenticatedTilaaPlusRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/gdpr': typeof AuthenticatedAdminGdprRoute
  '/_authenticated/admin/ilmoitukset': typeof AuthenticatedAdminIlmoituksetRoute
  '/_authenticated/admin/kayttajat': typeof AuthenticatedAdminKayttajatRoute
  '/_authenticated/admin/moderointi': typeof AuthenticatedAdminModerointiRoute
  '/_authenticated/admin/tapahtumat': typeof AuthenticatedAdminTapahtumatRoute
  '/_authenticated/admin/tilaukset': typeof AuthenticatedAdminTilauksetRoute
  '/_authenticated/ensifiilis/$id': typeof AuthenticatedEnsifiilisIdRoute
  '/_authenticated/plus/asetukset': typeof AuthenticatedPlusAsetuksetRoute
  '/_authenticated/plus/selaa': typeof AuthenticatedPlusSelaaRoute
  '/_authenticated/profiili/$id': typeof AuthenticatedProfiiliIdRoute
  '/_authenticated/treffijuttelu/$matchId': typeof AuthenticatedTreffijutteluMatchIdRoute
  '/_authenticated/viestit/$id': typeof AuthenticatedViestitIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/plus/': typeof AuthenticatedPlusIndexRoute
  '/_authenticated/viestit/': typeof AuthenticatedViestitIndexRoute
  '/_authenticated/plus/profiili/$id': typeof AuthenticatedPlusProfiiliIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hinnat'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/reset-password'
    | '/saannot'
    | '/tietoja'
    | '/tietosuoja'
    | '/tuki'
    | '/turvallisuus'
    | '/unohdin-salasanan'
    | '/admin'
    | '/aloitus'
    | '/asetukset'
    | '/hae'
    | '/kalenteri'
    | '/oma-profiili'
    | '/pisteet'
    | '/poistu'
    | '/radar'
    | '/ryhmat'
    | '/tapahtumat'
    | '/tilaa-plus'
    | '/auth/callback'
    | '/admin/gdpr'
    | '/admin/ilmoitukset'
    | '/admin/kayttajat'
    | '/admin/moderointi'
    | '/admin/tapahtumat'
    | '/admin/tilaukset'
    | '/ensifiilis/$id'
    | '/plus/asetukset'
    | '/plus/selaa'
    | '/profiili/$id'
    | '/treffijuttelu/$matchId'
    | '/viestit/$id'
    | '/admin/'
    | '/plus/'
    | '/viestit/'
    | '/plus/profiili/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hinnat'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/reset-password'
    | '/saannot'
    | '/tietoja'
    | '/tietosuoja'
    | '/tuki'
    | '/turvallisuus'
    | '/unohdin-salasanan'
    | '/aloitus'
    | '/asetukset'
    | '/hae'
    | '/kalenteri'
    | '/oma-profiili'
    | '/pisteet'
    | '/poistu'
    | '/radar'
    | '/ryhmat'
    | '/tapahtumat'
    | '/tilaa-plus'
    | '/auth/callback'
    | '/admin/gdpr'
    | '/admin/ilmoitukset'
    | '/admin/kayttajat'
    | '/admin/moderointi'
    | '/admin/tapahtumat'
    | '/admin/tilaukset'
    | '/ensifiilis/$id'
    | '/plus/asetukset'
    | '/plus/selaa'
    | '/profiili/$id'
    | '/treffijuttelu/$matchId'
    | '/viestit/$id'
    | '/admin'
    | '/plus'
    | '/viestit'
    | '/plus/profiili/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/hinnat'
    | '/kayttoehdot'
    | '/kirjaudu'
    | '/rekisteroidy'
    | '/reset-password'
    | '/saannot'
    | '/tietoja'
    | '/tietosuoja'
    | '/tuki'
    | '/turvallisuus'
    | '/unohdin-salasanan'
    | '/_authenticated/admin'
    | '/_authenticated/aloitus'
    | '/_authenticated/asetukset'
    | '/_authenticated/hae'
    | '/_authenticated/kalenteri'
    | '/_authenticated/oma-profiili'
    | '/_authenticated/pisteet'
    | '/_authenticated/poistu'
    | '/_authenticated/radar'
    | '/_authenticated/ryhmat'
    | '/_authenticated/tapahtumat'
    | '/_authenticated/tilaa-plus'
    | '/auth/callback'
    | '/_authenticated/admin/gdpr'
    | '/_authenticated/admin/ilmoitukset'
    | '/_authenticated/admin/kayttajat'
    | '/_authenticated/admin/moderointi'
    | '/_authenticated/admin/tapahtumat'
    | '/_authenticated/admin/tilaukset'
    | '/_authenticated/ensifiilis/$id'
    | '/_authenticated/plus/asetukset'
    | '/_authenticated/plus/selaa'
    | '/_authenticated/profiili/$id'
    | '/_authenticated/treffijuttelu/$matchId'
    | '/_authenticated/viestit/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/plus/'
    | '/_authenticated/viestit/'
    | '/_authenticated/plus/profiili/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HinnatRoute: typeof HinnatRoute
  KayttoehdotRoute: typeof KayttoehdotRoute
  KirjauduRoute: typeof KirjauduRoute
  RekisteroidyRoute: typeof RekisteroidyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaannotRoute: typeof SaannotRoute
  TietojaRoute: typeof TietojaRoute
  TietosuojaRoute: typeof TietosuojaRoute
  TukiRoute: typeof TukiRoute
  TurvallisuusRoute: typeof TurvallisuusRoute
  UnohdinSalasananRoute: typeof UnohdinSalasananRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unohdin-salasanan': {
      id: '/unohdin-salasanan'
      path: '/unohdin-salasanan'
      fullPath: '/unohdin-salasanan'
      preLoaderRoute: typeof UnohdinSalasananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turvallisuus': {
      id: '/turvallisuus'
      path: '/turvallisuus'
      fullPath: '/turvallisuus'
      preLoaderRoute: typeof TurvallisuusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuki': {
      id: '/tuki'
      path: '/tuki'
      fullPath: '/tuki'
      preLoaderRoute: typeof TukiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietosuoja': {
      id: '/tietosuoja'
      path: '/tietosuoja'
      fullPath: '/tietosuoja'
      preLoaderRoute: typeof TietosuojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietoja': {
      id: '/tietoja'
      path: '/tietoja'
      fullPath: '/tietoja'
      preLoaderRoute: typeof TietojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saannot': {
      id: '/saannot'
      path: '/saannot'
      fullPath: '/saannot'
      preLoaderRoute: typeof SaannotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekisteroidy': {
      id: '/rekisteroidy'
      path: '/rekisteroidy'
      fullPath: '/rekisteroidy'
      preLoaderRoute: typeof RekisteroidyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kirjaudu': {
      id: '/kirjaudu'
      path: '/kirjaudu'
      fullPath: '/kirjaudu'
      preLoaderRoute: typeof KirjauduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayttoehdot': {
      id: '/kayttoehdot'
      path: '/kayttoehdot'
      fullPath: '/kayttoehdot'
      preLoaderRoute: typeof KayttoehdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinnat': {
      id: '/hinnat'
      path: '/hinnat'
      fullPath: '/hinnat'
      preLoaderRoute: typeof HinnatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tilaa-plus': {
      id: '/_authenticated/tilaa-plus'
      path: '/tilaa-plus'
      fullPath: '/tilaa-plus'
      preLoaderRoute: typeof AuthenticatedTilaaPlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tapahtumat': {
      id: '/_authenticated/tapahtumat'
      path: '/tapahtumat'
      fullPath: '/tapahtumat'
      preLoaderRoute: typeof AuthenticatedTapahtumatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ryhmat': {
      id: '/_authenticated/ryhmat'
      path: '/ryhmat'
      fullPath: '/ryhmat'
      preLoaderRoute: typeof AuthenticatedRyhmatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/poistu': {
      id: '/_authenticated/poistu'
      path: '/poistu'
      fullPath: '/poistu'
      preLoaderRoute: typeof AuthenticatedPoistuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pisteet': {
      id: '/_authenticated/pisteet'
      path: '/pisteet'
      fullPath: '/pisteet'
      preLoaderRoute: typeof AuthenticatedPisteetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oma-profiili': {
      id: '/_authenticated/oma-profiili'
      path: '/oma-profiili'
      fullPath: '/oma-profiili'
      preLoaderRoute: typeof AuthenticatedOmaProfiiliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalenteri': {
      id: '/_authenticated/kalenteri'
      path: '/kalenteri'
      fullPath: '/kalenteri'
      preLoaderRoute: typeof AuthenticatedKalenteriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hae': {
      id: '/_authenticated/hae'
      path: '/hae'
      fullPath: '/hae'
      preLoaderRoute: typeof AuthenticatedHaeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asetukset': {
      id: '/_authenticated/asetukset'
      path: '/asetukset'
      fullPath: '/asetukset'
      preLoaderRoute: typeof AuthenticatedAsetuksetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aloitus': {
      id: '/_authenticated/aloitus'
      path: '/aloitus'
      fullPath: '/aloitus'
      preLoaderRoute: typeof AuthenticatedAloitusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viestit/': {
      id: '/_authenticated/viestit/'
      path: '/viestit'
      fullPath: '/viestit/'
      preLoaderRoute: typeof AuthenticatedViestitIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/': {
      id: '/_authenticated/plus/'
      path: '/plus'
      fullPath: '/plus/'
      preLoaderRoute: typeof AuthenticatedPlusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/viestit/$id': {
      id: '/_authenticated/viestit/$id'
      path: '/viestit/$id'
      fullPath: '/viestit/$id'
      preLoaderRoute: typeof AuthenticatedViestitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treffijuttelu/$matchId': {
      id: '/_authenticated/treffijuttelu/$matchId'
      path: '/treffijuttelu/$matchId'
      fullPath: '/treffijuttelu/$matchId'
      preLoaderRoute: typeof AuthenticatedTreffijutteluMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiili/$id': {
      id: '/_authenticated/profiili/$id'
      path: '/profiili/$id'
      fullPath: '/profiili/$id'
      preLoaderRoute: typeof AuthenticatedProfiiliIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/selaa': {
      id: '/_authenticated/plus/selaa'
      path: '/plus/selaa'
      fullPath: '/plus/selaa'
      preLoaderRoute: typeof AuthenticatedPlusSelaaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus/asetukset': {
      id: '/_authenticated/plus/asetukset'
      path: '/plus/asetukset'
      fullPath: '/plus/asetukset'
      preLoaderRoute: typeof AuthenticatedPlusAsetuksetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ensifiilis/$id': {
      id: '/_authenticated/ensifiilis/$id'
      path: '/ensifiilis/$id'
      fullPath: '/ensifiilis/$id'
      preLoaderRoute: typeof AuthenticatedEnsifiilisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tilaukset': {
      id: '/_authenticated/admin/tilaukset'
      path: '/tilaukset'
      fullPath: '/admin/tilaukset'
      preLoaderRoute: typeof AuthenticatedAdminTilauksetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tapahtumat': {
      id: '/_authenticated/admin/tapahtumat'
      path: '/tapahtumat'
      fullPath: '/admin/tapahtumat'
      preLoaderRoute: typeof AuthenticatedAdminTapahtumatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderointi': {
      id: '/_authenticated/admin/moderointi'
      path: '/moderointi'
      fullPath: '/admin/moderointi'
      preLoaderRoute: typeof AuthenticatedAdminModerointiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kayttajat': {
      id: '/_authenticated/admin/kayttajat'
      path: '/kayttajat'
      fullPath: '/admin/kayttajat'
      preLoaderRoute: typeof AuthenticatedAdminKayttajatRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ilmoitukset': {
      id: '/_authenticated/admin/ilmoitukset'
      path: '/ilmoitukset'
      fullPath: '/admin/ilmoitukset'
      preLoaderRoute: typeof AuthenticatedAdminIlmoituksetRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gdpr': {
      id: '/_authenticated/admin/gdpr'
      path: '/gdpr'
      fullPath: '/admin/gdpr'
      preLoaderRoute: typeof AuthenticatedAdminGdprRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plus/profiili/$id': {
      id: '/_authenticated/plus/profiili/$id'
      path: '/plus/profiili/$id'
      fullPath: '/plus/profiili/$id'
      preLoaderRoute: typeof AuthenticatedPlusProfiiliIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminGdprRoute: typeof AuthenticatedAdminGdprRoute
  AuthenticatedAdminIlmoituksetRoute: typeof AuthenticatedAdminIlmoituksetRoute
  AuthenticatedAdminKayttajatRoute: typeof AuthenticatedAdminKayttajatRoute
  AuthenticatedAdminModerointiRoute: typeof AuthenticatedAdminModerointiRoute
  AuthenticatedAdminTapahtumatRoute: typeof AuthenticatedAdminTapahtumatRoute
  AuthenticatedAdminTilauksetRoute: typeof AuthenticatedAdminTilauksetRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminGdprRoute: AuthenticatedAdminGdprRoute,
  AuthenticatedAdminIlmoituksetRoute: AuthenticatedAdminIlmoituksetRoute,
  AuthenticatedAdminKayttajatRoute: AuthenticatedAdminKayttajatRoute,
  AuthenticatedAdminModerointiRoute: AuthenticatedAdminModerointiRoute,
  AuthenticatedAdminTapahtumatRoute: AuthenticatedAdminTapahtumatRoute,
  AuthenticatedAdminTilauksetRoute: AuthenticatedAdminTilauksetRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAloitusRoute: typeof AuthenticatedAloitusRoute
  AuthenticatedAsetuksetRoute: typeof AuthenticatedAsetuksetRoute
  AuthenticatedHaeRoute: typeof AuthenticatedHaeRoute
  AuthenticatedKalenteriRoute: typeof AuthenticatedKalenteriRoute
  AuthenticatedOmaProfiiliRoute: typeof AuthenticatedOmaProfiiliRoute
  AuthenticatedPisteetRoute: typeof AuthenticatedPisteetRoute
  AuthenticatedPoistuRoute: typeof AuthenticatedPoistuRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedRyhmatRoute: typeof AuthenticatedRyhmatRoute
  AuthenticatedTapahtumatRoute: typeof AuthenticatedTapahtumatRoute
  AuthenticatedTilaaPlusRoute: typeof AuthenticatedTilaaPlusRoute
  AuthenticatedEnsifiilisIdRoute: typeof AuthenticatedEnsifiilisIdRoute
  AuthenticatedPlusAsetuksetRoute: typeof AuthenticatedPlusAsetuksetRoute
  AuthenticatedPlusSelaaRoute: typeof AuthenticatedPlusSelaaRoute
  AuthenticatedProfiiliIdRoute: typeof AuthenticatedProfiiliIdRoute
  AuthenticatedTreffijutteluMatchIdRoute: typeof AuthenticatedTreffijutteluMatchIdRoute
  AuthenticatedViestitIdRoute: typeof AuthenticatedViestitIdRoute
  AuthenticatedPlusIndexRoute: typeof AuthenticatedPlusIndexRoute
  AuthenticatedViestitIndexRoute: typeof AuthenticatedViestitIndexRoute
  AuthenticatedPlusProfiiliIdRoute: typeof AuthenticatedPlusProfiiliIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAloitusRoute: AuthenticatedAloitusRoute,
  AuthenticatedAsetuksetRoute: AuthenticatedAsetuksetRoute,
  AuthenticatedHaeRoute: AuthenticatedHaeRoute,
  AuthenticatedKalenteriRoute: AuthenticatedKalenteriRoute,
  AuthenticatedOmaProfiiliRoute: AuthenticatedOmaProfiiliRoute,
  AuthenticatedPisteetRoute: AuthenticatedPisteetRoute,
  AuthenticatedPoistuRoute: AuthenticatedPoistuRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedRyhmatRoute: AuthenticatedRyhmatRoute,
  AuthenticatedTapahtumatRoute: AuthenticatedTapahtumatRoute,
  AuthenticatedTilaaPlusRoute: AuthenticatedTilaaPlusRoute,
  AuthenticatedEnsifiilisIdRoute: AuthenticatedEnsifiilisIdRoute,
  AuthenticatedPlusAsetuksetRoute: AuthenticatedPlusAsetuksetRoute,
  AuthenticatedPlusSelaaRoute: AuthenticatedPlusSelaaRoute,
  AuthenticatedProfiiliIdRoute: AuthenticatedProfiiliIdRoute,
  AuthenticatedTreffijutteluMatchIdRoute:
    AuthenticatedTreffijutteluMatchIdRoute,
  AuthenticatedViestitIdRoute: AuthenticatedViestitIdRoute,
  AuthenticatedPlusIndexRoute: AuthenticatedPlusIndexRoute,
  AuthenticatedViestitIndexRoute: AuthenticatedViestitIndexRoute,
  AuthenticatedPlusProfiiliIdRoute: AuthenticatedPlusProfiiliIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HinnatRoute: HinnatRoute,
  KayttoehdotRoute: KayttoehdotRoute,
  KirjauduRoute: KirjauduRoute,
  RekisteroidyRoute: RekisteroidyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaannotRoute: SaannotRoute,
  TietojaRoute: TietojaRoute,
  TietosuojaRoute: TietosuojaRoute,
  TukiRoute: TukiRoute,
  TurvallisuusRoute: TurvallisuusRoute,
  UnohdinSalasananRoute: UnohdinSalasananRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
